development:
  adapter: postgresql
  database: apirails_development
  username: postgres
  password: Abixel2096
  host: localhost
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: apirails_test
  username: postgres
  password: Abixel2096
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: apirails_production
  username: postgres
  password: Abixel2096
  host: localhost
  pool: 5
  timeout: 5000
